# Generated by Django 3.2.9 on 2021-11-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
