# Generated by Django 3.2.9 on 2021-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmala',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='appmala/'),
        ),
    ]
