# Generated by Django 3.2.9 on 2021-11-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0002_auto_20211125_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
    ]
