# Generated by Django 3.2.9 on 2021-12-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
    ]
