# Generated by Django 3.2.9 on 2021-12-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0003_auto_20211203_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_id',
        ),
    ]
