# Generated by Django 3.2.9 on 2021-12-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
