# Generated by Django 3.2.9 on 2021-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0005_auto_20211204_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='store_id',
            new_name='store',
        ),
    ]
