# Generated by Django 3.2.9 on 2021-12-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0003_remove_store_user'),
        ('appmala', '0006_rename_store_id_review_store'),
    ]

    operations = [
    ]
