# Generated by Django 3.2.9 on 2021-12-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmala', '0007_merge_20211206_1507'),
        ('appmala', '0008_auto_20211206_1835'),
    ]

    operations = [
    ]
